name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target_arch: [ aarch64, arm, i686, x86_64 ]

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build
        run: ./amper run --jvm-args=${{ matrix.target_arch }}

      - name: Save Packages
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v5
        with:
          name: packages-${{ matrix.target_arch }}
          path: './termux-packages-master/output'

  test-android:
    name: Test (Android)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [ 23, 35 ]
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: actions/cache@v5
        with:
          path: ${{ env.CI_CACHED_PATHS }}
          key: ${{ runner.os }}-gradle-android-${{ hashFiles('**/libs.versions.toml', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-android-

      - name: Test (Android ${{ matrix.api-level }})
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: ./gradlew androidConnectedCheck --no-daemon

      - name: Save Test Reports (Android ${{ matrix.api-level }})
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v5
        with:
          name: test-reports-android-${{ matrix.api-level }}
          path: '**/build/reports/androidTests'